version: '0.2'
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - autoinstallers
  - blobless
  - clazz
  - GVFS
  - humanish
  - inversify
  - Positionals
  - rushstack
  - Sparo
  - tiktok
  - yargs
ignoreWords: []
import: []
